[project]
name = "fruitninjawebcam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.21",
    "opencv-python>=4.11.0.86",
    "pygame>=2.6.1",
    "shapely>=2.1.1",
]
